### ISSUE TITLE
Escaping issue

### ISSUE THREAD

**Issue by evenfrost** [zimme/meteor-iron-router-active#11]
When I try to escape any symbol in regex, Meteor throws parse error:
```
Errors prevented startup:                  
While building the application:
native: Unexpected token ? (compiling client/views/layout/layout.html)
```
In case of (as an example):
```html
<li class="{{isActivePath regex='reports\?'}}"><a href="{{pathFor 'reports'}}">Reports</a></li>
```

**Comment by zimme** [comment]
Could you give me an example regex that results in this error and I'll take
a look tonight

**Comment by zimme** [comment]
Sorry, didn't see the example in the email

**Comment by zimme** [comment]
Ok, a quick workaround is to use a helpers to define the regex string

```coffeescript
Template.test.helpers
  regex: 'reports\?'
```

```html
<li class="{{isActivePath regex=regex"><a href="/">home</a></li>
```

I'll continue to check this out, I believe it have something to do with how Blaze parse helpers in templates

**Comment by zimme** [comment]
Ok, If you escape the questionmark with \\? it should work

**Comment by evenfrost** [comment]
Got it, thanks.
