### ISSUE TITLE
_.capitalize not recognizing 

### ISSUE THREAD

**Issue by kevohagan** [zimme/meteor-iron-router-active#18]
im getting undefined is not a function

**Comment by zimme** [comment]
Sorry, just made a quick change of library to the official. Didn't realize the api was different.

**Comment by kevohagan** [comment]
mmm nope , im getting s is not defined 

```coffee
  name = name + 'Active' + s.capitalize type
```

**Comment by zimme** [comment]
This is fixed in `1.0.4`.

I'm so sorry for the inconvenience, I really need to implement tests as this could have been avoided.

I shouldn't push new releases after I've done quick fixes on the coffee break. :stuck_out_tongue_closed_eyes:

**Comment by kevohagan** [comment]
ha :) no worries! Thanks for the work! great job
