### ISSUE TITLE
Upgrade from 1.0.1 to 1.0.2 seems to conflict with currentUser

### ISSUE THREAD

**Issue by jtolla** [zimme/meteor-iron-router-active#19]
Not sure how or why, but my {{#if currentUser}}'s weren't being recognized after the update. Brought the package back down to 1.0.1 and everything worked fine again.

**Comment by zimme** [comment]
try 1.0.3 and see if it's related to #18 somehow

**Comment by zimme** [comment]
This is hopefully fixed in `1.0.4`. If it is, please close this issue.

**Comment by zimme** [comment]
@jtolla: Is this fixed with version `1.0.4`?

**Comment by jtolla** [comment]
Fixed!
