### ISSUE TITLE
'Starts with' regex (^) not triggering

### ISSUE THREAD

**Issue by paulisloud** [zimme/meteor-iron-router-active#25]
Here is the code snippet I'm using:

`<li class="{{isActiveRoute regex='^feeds'}}"><a href="/feeds">Feeds</a></li>`

Note the carat in the regex parameter. Without the carat this renders just fine, on the base route (/feeds), but obviously not with sub-routes. Using the carat, the active trigger does not happen on either the base route or sub-routes.

**Comment by zimme** [comment]
What are the names of the routes?

You're using `isActiveRoute` which matches against a route's name and not the route's path.

If the routes' name were like this: `feed.index`, `feed.show`, `feed.edit` then `^feed` would match.

In your case it seems like you wanna match against the paths.

`<li class="{{isActiveRoute regex='^\\/feeds'}}"><a href="/feeds">Feeds</a></li>`

**Comment by paulisloud** [comment]
Ah good to know re: isActivePath. Thanks for the updated regex, worked like a charm with isActivePath.
